In [61]:
import numpy as np
import matplotlib.pyplot as plt

#### Домашнее задание:
Задание 1: Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.


In [98]:
def calc_logloss(y, y_pred):
    b=0.001
    y_pred = np.clip(y_pred, a_min = b, a_max = 1-b)
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

#### Задание 2: Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.


In [99]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 
               1, 3, 3, 1, 2]], dtype = np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [100]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

#### Logistic Regression

In [101]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    errors = []
    Weights = []
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        errors.append(err)
        Weights.append(W)
    errors = np.array(errors)
    return errors, Weights

In [104]:
for alpha in [0.5, 0.1, 0.06, 0.01, 0.001, 0.0001, 0.00001]:
    errors_list, weights_list = eval_model(X, y, iterations = 30000, alpha = alpha )
    print(errors_list[-1])
    print(weights_list[-1])
    

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


3.4543778896578603
[ -429.85317529 -1066.13770889   238.3137846   1529.22336152]
3.4543778896578603
[ -85.52302012 -213.57577966   46.16187953  307.08382704]
3.4543778896578603
[ -50.84531439 -129.49745754   14.22166175  184.96716266]
3.4543778896578594
[ -8.13752042 -21.41610519  -1.37840032  32.0611602 ]
3.4543778896578603
[-0.39762246 -2.18272191  0.09458209  4.55638155]
1.9083682908826063
[ 0.36579954 -0.30544036  0.03969501  1.80354203]
0.8429606038958551
[ 0.4783702  -0.14856914 -0.00413787  1.54314539]


#### Задание 3: Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).


In [68]:
def calc_pred_proba(W, X):
    y_forecast = 1 / (1 + np.exp(-np.dot(W,X)))
    return y_forecast

In [69]:
calc_pred_proba(weights_list[-1], X)

array([0.45091443, 0.26368886, 0.53691502, 0.3516191 , 0.05229711,
       0.21391627, 0.13439504, 0.00957292, 0.50262493, 0.29122261])

#### Задание 4: Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).


In [75]:
def calc_pred(W, X, level):
    y_prognoz = calc_pred_proba(W, X)
    y_prognoz = np.where(y_prognoz > level, 1, 0)
    return y_prognoz

In [77]:
calc_pred(weights_list[-1], X, 0.5)

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

#### Задание 5: Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.


In [82]:
def accuracy (y, y_pred):
    Score = y == y_pred
    return Sum(Score)/len(y)

In [ ]:
def matrix_mistakes(y, y_pred):
    matrix_mistakes = np.zeros(shape = (2,2)
    matrix_mistakes[0,0] = np.sum(np.where(y == 0, y_pred == y, False))
    matrix_mistakes[1,1] = np.sum(np.where(y == 1, y_pred == y, False))
    matrix_mistakes[1,0] = np.sum(np.where(y == 1, y_pred == y, False))
    matrix_mistakes[0,1] = len(y) - matrix_mistakes.sum()
    
    return matrix_mistakes,astype(int)
                               

Задание 6: Могла ли модель переобучиться? Почему?


In [ ]:
Обычно переобучение происходит при увеличении сложности модели, когда модель стремится описать все возможные состояния системы.
У нас пока этого не призошло, об этом и говорят коэффициенты весов, которые в норме для приемлемых значений альфа.